2024-12-28 13:58:50,869 / WARNING / Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Дима\Python project\Домашние задания\Testdir\tests_12_4.py", line 71, in test_run
    tr = Runner(6)
  File "D:\Дима\Python project\Домашние задания\Testdir\tests_12_4.py", line 9, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-28 13:58:50,878 / WARNING / Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Дима\Python project\Домашние задания\Testdir\tests_12_4.py", line 57, in test_walk
    tw = Runner('tw', -98)
  File "D:\Дима\Python project\Домашние задания\Testdir\tests_12_4.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -98
